name: CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: Docker Build & Push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/career-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/career-backend:latest

      - name: EC2 서버에 SSH 접속 후 컨테이너 재시작
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/career-backend:latest
            docker stop careeroom-container || true
            docker rm careeroom-container || true
            docker run -d --name careeroom-container \
              --env-file /home/ubuntu/backend/.env \
              -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/career-backend:latest
